### ISSUE TITLE
Define API Structure for Backend

### ISSUE THREAD

**Issue by OwlHaus** [Women-in-Computing-at-RIT/poll-system#14]
While we have the basis of these documented, we need to further define these so that we can actually create the API calls in a standardized format

**Comment by OwlHaus** [comment]
@dquach217 If you could please formalize the API structure:
This includes defining a list of all API calls(POST, PUT, DELETE, etc)
For each call define what the endpoint will be labeled as, for example /create/poll, /add/admin
For each call we need to define how data will be passed, say through json, url parameters, etc

**Comment by dquach217** [comment]
**App**
GET `v1/app/polls/{poll_id}`

POST `v1/app/polls/`

PUT `v1/app/polls/{poll_id}`

**OAuth**

GET `v1/app/oauth/`

POST `v1/app/oauth/`

**Slack**

GET `v1/slack/polls/{poll_id}`

GET `v1/slack/polls/all`

POST `v1/slack/polls/`

PUT `v1/slack/polls/{poll_id}`

DELETE `v1/slack/polls/{poll_id}`

**Admin**

GET `v1/admin/polls/{poll_id}`

GET `v1/admin/polls/all`

PUT `v1/admin/polls/{poll_id}`

DELETE `v1/admin/polls/{poll_id}`

**Super Admin / Project Head**

PUT `v1/admin/{superAdmin}/{user_id}`
