### ISSUE TITLE
Make High Level ERD For Database

### ISSUE THREAD

**Issue by OwlHaus** [Women-in-Computing-at-RIT/poll-system#19]
Need a High Level ERD for Database Object Relationships. This will be used to implement the design of the DB

**Comment by gen1e** [comment]
I think I got everything, it's in the 18-19 folder on the drive under poll_docs in the lucidchart names poll-db.
![poll-db](https://user-images.githubusercontent.com/15071353/49249418-0cf3c800-f3ea-11e8-9cde-b0ffe72223be.png)
